package tn.cloudcrafters.picloud.entity.gestionboutique;

import jakarta.persistence.*;
import jakarta.validation.constraints.*;
import lombok.Data;
import java.util.List;

@Entity
@Data
public class Produit {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @NotBlank(message = "Le nom du produit est obligatoire")
    private String nom;

    @NotNull(message = "Le prix est obligatoire")
    @Positive(message = "Le prix doit être positif")
    private Double prix;

    @NotNull(message = "La quantité est obligatoire")
    @PositiveOrZero(message = "La quantité ne peut pas être négative")
    private Integer quantite;

    @ManyToOne
    @JoinColumn(name = "categorie_id")
    private Categorie categorie;

    @OneToMany(mappedBy = "produit", cascade = CascadeType.ALL)
    private List<ImageProduit> images;

    @OneToMany(mappedBy = "produit")
    private List<LigneCommande> ligneCommandes;

    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
    }

    // Remove the manual getter and setter methods
    // They are automatically generated by @Data
}